root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "main"
full_bin = "./main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
exclude_regex = ["_test.go"]

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true
